// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokeTeamBuilder.BlazorServer.Data;

#nullable disable

namespace PokeTeamBuilder.BlazorServer.Migrations
{
    [DbContext(typeof(PokemonContext))]
    [Migration("20221117224243_MadePropertiesNullable")]
    partial class MadePropertiesNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("PokeTeamBuilder.BlazorServer.Data.PokemonTeamMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ability")
                        .HasColumnType("TEXT");

                    b.Property<string>("Held_Item")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("move1")
                        .HasColumnType("TEXT");

                    b.Property<string>("move2")
                        .HasColumnType("TEXT");

                    b.Property<string>("move3")
                        .HasColumnType("TEXT");

                    b.Property<string>("move4")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("PokemonTeamMembers");
                });

            modelBuilder.Entity("PokeTeamBuilder.BlazorServer.Data.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TeamName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("PokeTeamBuilder.BlazorServer.Data.PokemonTeamMember", b =>
                {
                    b.HasOne("PokeTeamBuilder.BlazorServer.Data.Team", "Team")
                        .WithMany("PokemonTeamMembers")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("PokeTeamBuilder.BlazorServer.Data.Team", b =>
                {
                    b.Navigation("PokemonTeamMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
