// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokeTeamBuilder.BlazorServer.Data;

#nullable disable

namespace PokeTeamBuilder.BlazorServer.Migrations
{
    [DbContext(typeof(PokemonContext))]
    partial class PokemonContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("PokeTeamBuilder.BlazorServer.Data.PokemonTeamMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ability")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("move1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("move2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("move3")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("move4")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("PokemonTeamMembers");
                });

            modelBuilder.Entity("PokeTeamBuilder.BlazorServer.Data.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("PokeTeamBuilder.BlazorServer.Data.PokemonTeamMember", b =>
                {
                    b.HasOne("PokeTeamBuilder.BlazorServer.Data.Team", "Team")
                        .WithMany("PokemonTeamMember")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("PokeTeamBuilder.BlazorServer.Data.Team", b =>
                {
                    b.Navigation("PokemonTeamMember");
                });
#pragma warning restore 612, 618
        }
    }
}
